version: '3.1'

networks:
  near-bye-network:
    external: true

services:
  app:
    container_name: near-bye-backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
      - rsa-keys-dev/private.test.pem.env
      - rsa-keys-dev/public.test.pem.env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - 3001:3001
    networks:
      - near-bye-network
    depends_on:
      - backend-db
  backend-db:
    container_name: near-bye-backend-db
    restart: always
    image: postgres
    build:
      dockerfile: Dockerfile-db
      context: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: backend-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./tmp/pgdata/backend:/var/lib/postgresql/data
    networks:
      - near-bye-network
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    networks:
      - near-bye-network
